### ISSUE TITLE
The plugin `flutter_bugfender` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by sarbogast** [bugfender/BugfenderSDK-Flutter#15]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

This is the error message I get when trying to build my project with flutter_bugfender 2.0.0-web.1 on Flutter 2.5.0.

**Comment by jgimenez** [comment]
Thanks Sebastien, we'll look into it.

**Comment by dannygmr** [comment]
@jgimenez i have a fix for the issue. How can i make a PR?

**Comment by jgimenez** [comment]
Hi @dannygmr , that's great! You can submit a PR like this: https://opensource.com/article/19/7/create-pull-request-github

**Comment by dannygmr** [comment]
> Hi @dannygmr , that's great! You can submit a PR like this: https://opensource.com/article/19/7/create-pull-request-github

It seems that i don't have a permission to push a new branch for some reason...
![image](https://user-images.githubusercontent.com/12214379/133100761-5093d951-57db-4bdf-8f60-218fac5a3d55.png)

**Comment by jgimenez** [comment]
Resolved in #20
