### ISSUE TITLE
Publish 2.0.1 to pub.dev

### ISSUE THREAD

**Issue by shilangyu** [bugfender/BugfenderSDK-Flutter#21]
I see android embedding and jcenter were fixed, but not yet published to pub.dev. Is there a blocker?

**Comment by jgimenez** [comment]
We're still testing this version and will probably be published this week. If you're in a hurry to get what's in master, please feel free to compile from source.

**Comment by franmontiel** [comment]
Hi, the version 2.0.1 plugin has been published to pub.dev
