### ISSUE TITLE
Failing to build with 2.0.1

### ISSUE THREAD

**Issue by kmaxion** [bugfender/BugfenderSDK-Flutter#22]
Hi, 

I'm running into a compile issue on Android since version 2.0.1 came out. Works fine when I use 2.0.0.
Here's the error:

`FAILURE: Build failed with an exception.
 What went wrong:
 Could not determine the dependencies of task ':flutter_bugfender:compileReleaseAidl'.
 Failed to query the value of task ':flutter_bugfender:compileReleaseAidl' property 'aidlFrameworkProvider'.
 Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.`

**Comment by mkucharski17** [comment]
This is probably not a problem with the package but with your android studio. Check this link. https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted/68430992#68430992
