### ISSUE TITLE
Exception caught by Flutter framework : Zone mismatch

### ISSUE THREAD

**Issue by joe-mybuzz** [bugfender/BugfenderSDK-Flutter#33]
Hello Bugfender team,

I found an error when wrapping the runApp() with the `FlutterBugfender.handleUncaughtErrors` function:

![image](https://github.com/bugfender/BugfenderSDK-Flutter/assets/114913009/bce66acd-c3ca-4f8a-8fef-14956ff5f64e)
```
Zone mismatch. The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set. It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later. To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
```

Based on this [doc](https://docs.flutter.dev/release/breaking-changes/zone-errors), starting with Flutter 3.10, the framework detects mismatches when using Zones and reports them to the console in debug builds. We are currently using Flutter 3.16.5.

Is there a solution for this?

**Comment by joe-mybuzz** [comment]
Hi @jgimenez! Thank you for your reply. I tried it out and what I did was move the `WidgetsFlutterBinding.ensureInitialized()` and other functions and methods that rely on the `WidgetsFlutterBinding.ensureInitialized()` to run first into the same closure as `runApp()`.

**Comment by jgimenez** [comment]
Great, thanks for confirming this works. Then we'll apply the same in the SDK and instructions.
