### ISSUE TITLE
Consider upgrading js library to 0.7.1

### ISSUE THREAD

**Issue by rignaneseleo** [bugfender/BugfenderSDK-Flutter#39]
I get this error: 

```
Because flutter_bugfender 2.3.0 depends on js ^0.6.3 and no versions of flutter_bugfender match >2.3.0 <3.0.0, flutter_bugfender ^2.3.0 requires js ^0.6.3.
So, because onda depends on both flutter_bugfender ^2.3.0 and js ^0.7.1, version solving failed.
```

It would be great if the js library can be upgraded to the v0.7.1
Thanks!

**Comment by jgimenez** [comment]
Hi @rignaneseleo , thanks for sharing. Would you like to contribute a PR for it?

**Comment by andrewfam** [comment]
What would this entail? Can i just update the pubspec to 0.7.1? I'm facing the same issue

**Comment by aliaksei-liavonik** [comment]
Hi, it's impossible to use new versions of google maps, since they set minimum version of js to 0.7.1, could you bump it?
Thanks in advance!

**Comment by aliaksei-liavonik** [comment]
@jgimenez, could u check the pr i've created? There is no any pipelines with checks or any tests, so I've run example project and pressed all the buttons, seems to work ok, but I'm not sure it's good way to test the package, so could you elaborate?

**Comment by jgimenez** [comment]
Updated in #45 and version [3.1.0](https://pub.dev/packages/flutter_bugfender/versions/3.1.0) released. Thanks @aliaksei-liavonik for your contribution!
