### ISSUE TITLE
Updating the package on pub.dev

### ISSUE THREAD

**Issue by orestesgaolin** [bugfender/BugfenderSDK-Flutter#4]
Is there any possibility that the package available [here](https://pub.dev/packages/flutter_bugfender) will be updated to current version in this repository?

**Comment by jgimenez** [comment]
Hi there, for now we recommend you depend on the git repository, since the newest version is only available here. We're in contact with the owner of the pub.dev repository in order to see how we move forward.

**Comment by orestesgaolin** [comment]
Thanks for the response! I hope you settle on some solution soon. Till then I'll just use the git repository as suggested.

**Comment by orestesgaolin** [comment]
@jgimenez is there any update on this issue? Are you able to update package on pub.dev?

**Comment by jgimenez** [comment]
Hi @orestesgaolin , yes, we got access, we're going to do an update soon. For now we recommend using the git repository instead of pub.dev

**Comment by jgimenez** [comment]
Done on 4051646 !
