### ISSUE TITLE
dSYM issues in XCode 16

### ISSUE THREAD

**Issue by sarbogast** [bugfender/BugfenderSDK-Flutter#41]
As I am trying to upload the latest archive of my app to AppStoreConnect inside of XCode 16, I see a couple of error messages:

<img width="1024" alt="Screenshot 2024-09-24 at 15 45 54" src="https://github.com/user-attachments/assets/486bfc4f-f197-4352-a784-61272d3a3b62">

```
Asset validation failed
Invalid Executable. The executable 'Runner.app/Frameworks/BugfenderSDK.framework/BugfenderSDK' contains bitcode. (ID: 99c40f86-4078-4f0c-a023-4a47766ff87b)

Upload Symbols Failed
The archive did not include a dSYM for the BugfenderSDK.framework with the UUIDs [7CC24511-F97C-30FB-AB03-951B7FA8DFD8]. Ensure that the archive's dSYM folder includes a DWARF file for BugfenderSDK.framework with the expected UUIDs.
```

Note: I am also trying to integrate Crashlytics into my app in this release, I don't know if it's related.

**Comment by ventayol** [comment]
Hi @sarbogast, this is a change Apple did in the recent weeks. Are you using the latest version of the SDK? Be sure that you are using at least version 3.0.0, which should fix this problem.
If you are already using this version and you are experiencing the same problem, let us know to analyze the problem in detail.

**Comment by sarbogast** [comment]
Indeed, once I use 3.0.0+1, I don't have the error anymore. Thanks
