### ISSUE TITLE
Flutter looking for bugfender files that not exists yet in maven repo

### ISSUE THREAD

**Issue by Kendru98** [bugfender/BugfenderSDK-Flutter#43]
> Failed to transform android-3.3.2.aar (com.bugfender.sdk:android:3.3.2) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
	      > Could not find android-3.3.2.jar (com.bugfender.sdk:android:3.3.2).
	        Searched in the following locations:
	            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.aar
	            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.jar

**Comment by fromkeith** [comment]
related: https://github.com/bugfender/BugfenderSDK-android-sample/issues/18

I've also contacted Bugfender support. They said their Android team is looking into it.

**Comment by karoliam** [comment]
Same problem here! I hope this issue gets resolved soon, not being able to build the app is very inconvenient. Are there any workarounds?

**Comment by ufiprogrammer4** [comment]
I also have the same problem, is there any alternative while waiting for the developer to fix this?

**Comment by wimansha** [comment]
Got my new release blocked with the error below. Please help.

FAILURE: Build failed with an exception.

Execution failed for task ':flutter_bugfender:generateReleaseRFile'.
> Could not resolve all files for configuration ':flutter_bugfender:releaseCompileClasspath'.
   > Failed to transform android-3.3.2.aar (com.bugfender.sdk:android:3.3.2) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find android-3.3.2.aar (com.bugfender.sdk:android:3.3.2).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.aar
            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.jar

**Comment by jgimenez** [comment]
Hi there,
As you mentioned, the maven package for version 3.3.2 released yesterday was malformed and was missing the .aar file.
Our engineers released version 3.3.3 with the corrected package a few minutes ago.
Please try rebuilding your project, and that should fix the problems you are experiencing. If you keep experiencing any issues, please let me know so we can look into it.

**Comment by android-imdad** [comment]
As a temporary fix you can also open the flutter plugins folder - flutter_bugfender - android - build.gradle  and change line number 41 in android build.gradle

from -
implementation 'com.bugfender.sdk:android:3.+'

To -
implementation 'com.bugfender.sdk:android:3.3.3'
