### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by sarbogast** [bugfender/BugfenderSDK-Flutter#8]
I have an application that integrates this SDK and works great on Android and iOS. But even though the plugin page says it should also work in a web context, when I try to run my app on the web, I get the following error in the console:

> html_dart2js.dart:39777 Overflow on channel: flutter_bugfender.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
> error @ html_dart2js.dart:39777
> _printDebugString @ natives.dart:23
> _printDebug @ natives.dart:15
> push @ channel_buffers.dart:147
> handlePlatformMessage @ plugin_registry.dart:82
> runBody @ async_patch.dart:86
> _async @ async_patch.dart:125
> handlePlatformMessage @ plugin_registry.dart:76
> [_sendPlatformMessage] @ window.dart:450
> sendPlatformMessage @ window.dart:318
> [_sendPlatformMessage] @ binding.dart:167
> send @ binding.dart:223
> _invokeMethod @ platform_channel.dart:146
> runBody @ async_patch.dart:86
> _async @ async_patch.dart:125
> [_invokeMethod] @ platform_channel.dart:144
> invokeMethod @ platform_channel.dart:329
> removeDeviceString @ flutter_bugfender.dart:25
> (anonymous) @ main.dart:93
> (anonymous) @ stream.dart:901
> _runUserCode @ stream_pipe.dart:13
> (anonymous) @ stream.dart:901
> runUnaryGuarded @ zone.dart:1374
> [_sendData] @ stream_impl.dart:339
> [_add] @ stream_impl.dart:266
> [_add] @ stream_pipe.dart:134
> [_handleData] @ stream_pipe.dart:234
> [_handleData] @ stream_pipe.dart:166
> runUnaryGuarded @ zone.dart:1374
> [_sendData] @ stream_impl.dart:339
> [_add] @ stream_impl.dart:266
> [_add] @ stream_pipe.dart:134
> [_handleData] @ stream_pipe.dart:234
> [_handleData] @ stream_pipe.dart:166
> runUnaryGuarded @ zone.dart:1374
> [_sendData] @ stream_impl.dart:339
> [_add] @ stream_impl.dart:266
> [_sendData] @ broadcast_stream_controller.dart:378
> add @ broadcast_stream_controller.dart:252
> (anonymous) @ auth.dart:306
> _checkAndCall @ operations.dart:305
> dcall @ operations.dart:311
> ret @ js_patch.dart:412
> (anonymous) @ firebase-app.js:1
> (anonymous) @ firebase-app.js:1
> Show 15 more frames
> errors.dart:146 Uncaught (in promise) Error: MissingPluginException(No implementation found for method init on channel flutter_bugfender)
>     at Object.throw_ [as throw] (errors.dart:195)
>     at MethodChannel._invokeMethod (platform_channel.dart:154)
>     at _invokeMethod.next (<anonymous>)
>     at onValue (async_patch.dart:47)
>     at _RootZone.runUnary (zone.dart:1439)
>     at _FutureListener.thenAwait.handleValue (future_impl.dart:141)
>     at handleValueCallback (future_impl.dart:682)
>     at Function._propagateToListeners (future_impl.dart:711)
>     at _Future.new.[_completeWithValue] (future_impl.dart:526)
>     at async._AsyncCallbackEntry.new.callback (future_impl.dart:556)
>     at Object._microtaskLoop (schedule_microtask.dart:43)
>     at _startMicrotaskLoop (schedule_microtask.dart:52)
>     at async_patch.dart:168
> 

Did you test your plugin in a web context? And if not, would it be possible for you to add explicit web support?

**Comment by jgimenez** [comment]
Hi @sarbogast , this project is an adapter (glue code) for the iOS and Android SDKs to work on Flutter, so it's not really meant to work on the web (I'm guessing the "web" label in [pub.dev](https://pub.dev/packages/flutter_bugfender) is misleading, I don't know why it's there). Bugfender is soon going to release a web SDK, so I guess it will be possible to also add the web SDK adapter in the future.

**Comment by sarbogast** [comment]
In the bugfender doc, they say that until their web SDK is ready (which I’m guessing is going to be for popular web frameworks like React or Angular anyway), we can use the REST API. Isn’t that a possibility?

---
Sébastien Arbogast
http://sebastien-arbogast.com ( https://share.polymail.io/v1/z/b/NWU5ZDdhZGRhNWVj/UZQwW7rIQLsWwrUVPlpWL9Jvw7WOeEmrk-n_dC8FO1N0etNs2GqiMQknjuV4LZTs7JY54qekbTqUVpp8tFCro3A9kESNqm0vLc4ikpV0KxYP5HUMMdxQOS4tfu8QVv1ZUUFLKx2aZwfJi-yLWoodvD72tWGLZSIV8yrKr05kAb-uhiWdDn1EG8I1lPHPzjuImVNSUYTeC5t3XaxZBb_jakJKhkW92IuxmUK4qvxxf42KKv_4zpNjSJ8p )

**Comment by jgimenez** [comment]
Sorry, there is no public API at the moment. Where did you see that? We might have to update the docs

**Comment by sarbogast** [comment]
> Q: Does Bugfender only work with mobile devices?
> We currently support iOS and Android. Other platforms will follow including web, Windows and macOS. For now, you can send logs from those through our API.

[https://bugfender.com/faq/](https://bugfender.com/faq/)

**Comment by jgimenez** [comment]
Thanks, that page is really old and outdated. I deleted it.

**Comment by sarbogast** [comment]
Now that there is a web SDK for Bugfender, would it be possible to add web support to this package?

**Comment by jgimenez** [comment]
Yes, it is possible! If you'd like to contribute, please feel free to open a PR!

**Comment by jgimenez** [comment]
I looked into this, and it seems like logging in a Flutter app is done by the backend, which is not supported currently by Bugfender. Bugfender at the moment only supports web frontend logging, so for now this is not possible.

**Comment by sarbogast** [comment]
What do you mean be "it seems like logging in a Flutter app is done by the backend". There is no backend in a Flutter app, or at least it's completely independent. Even a Flutter web app works like a SPA, with a boat load of javascript doing stuff in the browser, and you don't need a backend to log, not a backend on a server anyway.

**Comment by jgimenez** [comment]
In that case I misunderstood how it works! When I run a flutter app with `flutter run`, the application is run by a server, not by static files. Bugfender could still be used, then, but I'm not really sure how. Unfortunately the flutter documentation for web is not very extensive yet.

**Comment by sarbogast** [comment]
The best information I found about that is here: https://medium.com/flutter/how-to-write-a-flutter-web-plugin-5e26c689ea1
And second part is here: https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6

**Comment by jgimenez** [comment]
Thanks for the pointers. I found them but still they're pretty basic. Bugfender is distributed as an NPM package, so it would be good to find a way to import that package and then use it, just like it's possible to import iOS and Android packages using CocoaPods and gradle. I didn't find a way to do that (if it's possible)

**Comment by sarbogast** [comment]
I don't think it is possible, precisely because there is no node integration in the build system. We have the same problem with other plugins like the AppAuth one for oAuth authentication. Hopefully Google will release more documentation about how to port and develop plugins once Flutter web exits beta.

**Comment by jgimenez** [comment]
I see. In that case I think it would be better to wait for a npm support so we don't have to embed the JS file in the plugin itself. I guess then it would be a matter of loading that script with a <script> tag and bridge all the calls, similar to this: https://medium.com/flutter-community/using-javascript-code-in-flutter-web-903de54a2000

**Comment by jgimenez** [comment]
@sarbogast since you were interested in this, I'd love your feedback on #14 if you'd like to test

**Comment by jgimenez** [comment]
Published in `2.0.0-web.1`
